footprint: [[-0.45,-0.20], [-0.45,0.20], [0.10,0.20], [0.10,-0.20]]

obstacle_layer:
   observation_sources: scan
   scan: 
      sensor_frame: /laser
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      expected_update_rate: 5.0
   obstacle_range: 2.
   raytrace_range: 3.0

inflation_layer:
   inflation_radius: 0.5
