base_global_planner: navfn/NavfnROS
recovery_behaviors:  [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
planner_patience: 15.0
clearing_rotation_allowed: false

controller_frequency: 10.0
