base_local_planner: dwa_local_planner/DWAPlannerROS
#base_local_planner: base_local_planner/TrajectoryPlannerROS

DWAPlannerROS:
   acc_lim_th: 3.2
   acc_lim_x: 0.8
   acc_lim_y: 0.0

   max_trans_vel: 0.75
   min_trans_vel: 0.25
   max_vel_x: 0.75
   min_vel_x: 0.25
   max_vel_y: 0
   min_vel_y: 0

   max_rot_vel: 1.0
   min_rot_vel: 0.4

   yaw_goal_tolerance: 0.1
   xy_goal_tolerance: 0.5

   sim_time: 3.0
   sim_granularity: 0.05
   penalize_negative_x: false

   vth_samples: 20
   vtheta_samples: 20
   vx_samples: 20
   vy_samples: 1
